# Generated by Django 2.2.5 on 2020-11-10 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(1, 'Bar Foo'), (2, 'Bar Baz'), (3, 'Bar Qux'), (4, 'Bar Quux'), (5, 'Bar Corge'), (6, 'Bar Grault')], default=None, verbose_name='出勤場所名')),
                ('in_out', models.IntegerField(choices=[(1, 'IN'), (0, 'OUT')], default=None, verbose_name='IN/OUT')),
                ('time', models.TimeField(verbose_name='打刻時間')),
                ('date', models.DateField(verbose_name='打刻日')),
                ('staff', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
