# Generated by Django 3.1.3 on 2020-11-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20201110_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitattendance',
            name='in_out',
            field=models.IntegerField(choices=[(1, '出勤'), (0, '退勤')], default=None, verbose_name='IN/OUT'),
        ),
    ]
